# Generated by Django 2.2.2 on 2020-03-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email address')),
                ('id', models.CharField(default='89bea0b3-e25e-438a-b5b8-73dd2ee611d6', editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('displayName', models.CharField(max_length=30)),
                ('host', models.URLField(default='127.0.0.1:8000', max_length=100)),
                ('url', models.URLField(default='http:127.0.0.1:8000/accounts/author/profile/89bea0b3-e25e-438a-b5b8-73dd2ee611d6/', max_length=100)),
                ('avatar', models.ImageField(blank=True, default='avatar/default-avatar.png', null=True, upload_to='avatar/')),
                ('github', models.URLField(default='', max_length=100, null=True)),
                ('bio', models.CharField(default='', max_length=200, null=True)),
                ('date_joined', models.DateField(auto_now=True, verbose_name='date joined')),
                ('last_login', models.DateField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
