# Generated by Django 2.1.5 on 2020-03-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='127.0.0.1:8000', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='127.0.0.1:8000/author/53437c57-2874-4cc5-a55d-c189fababf41', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='127.0.0.1:8000/author/53437c57-2874-4cc5-a55d-c189fababf41', max_length=100),
        ),
    ]
