# Generated by Django 2.1.5 on 2020-03-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='db83dbb5-78d6-4e89-80b8-9aec794e6d2e', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
