# Generated by Django 2.2.2 on 2020-03-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='127.0.0.1:8000', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='12d009cd-1d4a-417a-94d7-25a7e93b83fb', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
