# Generated by Django 2.1.5 on 2020-03-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='28f5f568-0b9a-47de-ad53-72db9e1c2ea8', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
