# Generated by Django 2.2.2 on 2020-03-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200324_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_username', models.CharField(max_length=100)),
                ('server_password', models.CharField(max_length=100)),
                ('token', models.CharField(blank=True, max_length=200)),
                ('host_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='94202186-7b5c-4c74-be14-f3e580081d0f', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
