# Generated by Django 2.2.2 on 2020-04-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200327_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='http://127.0.0.1:8000/', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='af196dec-913f-4f16-b148-fd499c183560', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
