# Generated by Django 2.1.5 on 2020-03-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200305_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='127.0.0.1:8000/author/017355a4-3f98-4222-9612-6b4da46d973e', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='127.0.0.1:8000/author/017355a4-3f98-4222-9612-6b4da46d973e', max_length=100),
        ),
    ]
