# Generated by Django 2.2.2 on 2020-03-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200324_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='ec1f227a-16c9-48e5-883a-7a6969ab8793', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
