# Generated by Django 2.1.5 on 2020-03-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200305_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='3e6bf29e-d0c1-4981-adc8-1ea2cf5307d8', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='3e6bf29e-d0c1-4981-adc8-1ea2cf5307d8', max_length=100),
        ),
    ]
