# Generated by Django 2.2.2 on 2020-04-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200401_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='0f51b019-c20b-4608-99e1-fed1385d547e', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
