# Generated by Django 2.2.2 on 2020-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200324_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, default='This guy is too lazy to write a bio...', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='https://peaceful-savannah-82754.herokuapp.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='15e6b518-62f1-460f-90a9-c474a8969670', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
