# Generated by Django 2.1.5 on 2020-03-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200305_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='a77fd1be-0c95-46fb-a3d7-94652f1274b6', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='a77fd1be-0c95-46fb-a3d7-94652f1274b6', max_length=100),
        ),
    ]
