# Generated by Django 2.2.2 on 2020-03-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200326_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='bf45ec65-3d6f-4599-8f85-36765a815d25', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
