# Generated by Django 2.2.2 on 2020-04-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200401_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='aca49f7e-8ef0-4028-9926-5385e6e4f89d', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
