# Generated by Django 2.2.2 on 2020-03-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200326_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='edca4b38-db72-43d2-a05d-83f025976790', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
