# Generated by Django 2.1.5 on 2020-04-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200401_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='e6fb0c9f-7b27-43d6-9dfc-e2c92e5425dd', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
