# Generated by Django 2.2.2 on 2020-04-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200402_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='9dc282f1-2476-4588-875b-af07acfba9b4', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
