# Generated by Django 2.1.5 on 2020-03-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200307_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='cf655858-268e-4f2d-9f53-951dd0365aad', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='cf655858-268e-4f2d-9f53-951dd0365aad', max_length=100),
        ),
    ]
