# Generated by Django 2.2.2 on 2020-03-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200326_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='e1a8cf12-64e1-4f83-b921-c1c809da43cb', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
