# Generated by Django 2.2.2 on 2020-03-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200326_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='55f0ae28-ecbc-419d-82f1-6b09ed8a4990', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
