# Generated by Django 2.1.5 on 2020-03-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200307_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='63875259-0a1f-4bc7-bc0e-39891e2e2b24', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='63875259-0a1f-4bc7-bc0e-39891e2e2b24', max_length=100),
        ),
    ]
