# Generated by Django 2.2.2 on 2020-04-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200403_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='26fe4c33-7433-4e8b-91de-f1ff0357fe84', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
