# Generated by Django 2.2.2 on 2020-03-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200326_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='ab6bab75-71ab-456a-b80b-abf0e141198e', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
