# Generated by Django 2.1.5 on 2020-03-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200307_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='1b6b6397-a395-43fe-afe1-2acd0db8916a', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='1b6b6397-a395-43fe-afe1-2acd0db8916a', max_length=100),
        ),
    ]
