# Generated by Django 2.1.5 on 2020-03-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200309_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='c8a7f82f-9d0d-4f4c-880d-749a2cb90db8', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='c8a7f82f-9d0d-4f4c-880d-749a2cb90db8', max_length=100),
        ),
    ]
