# Generated by Django 2.2.2 on 2020-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200403_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='7323d589-9feb-4b6a-b219-93da2e52341a', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
