# Generated by Django 2.2.2 on 2020-04-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200403_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='c379f980-f361-472d-9543-05683dfb2e83', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
