# Generated by Django 2.1.5 on 2020-03-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200309_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='af0c92e8-37d6-4c11-ad12-bd71e36c5167', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='af0c92e8-37d6-4c11-ad12-bd71e36c5167', max_length=100),
        ),
    ]
