# Generated by Django 2.1.5 on 2020-03-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200309_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='4fb39d93-349b-42ea-9935-0ea14702999f', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='4fb39d93-349b-42ea-9935-0ea14702999f', max_length=100),
        ),
    ]
