# Generated by Django 2.2.2 on 2020-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200403_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='c1d4e86d-0727-422e-b275-e96f6047aceb', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
