# Generated by Django 2.1.5 on 2020-03-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200309_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='c8944562-ee2c-4b7b-8c90-b759c5671f42', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='localhost:8000/author/c8944562-ee2c-4b7b-8c90-b759c5671f42', max_length=100),
        ),
    ]
