# Generated by Django 2.1.5 on 2020-03-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200309_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='287cd332-9dbe-474e-9e34-d3f07498a93e', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='localhost:8000/accounts/author/profile/287cd332-9dbe-474e-9e34-d3f07498a93e', max_length=100),
        ),
    ]
