# Generated by Django 2.1.5 on 2020-03-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200309_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='09788ffe-e82f-45f9-99a0-88141e125942', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='http:127.0.0.1:8000/accounts/author/profile/09788ffe-e82f-45f9-99a0-88141e125942/', max_length=100),
        ),
    ]
