# Generated by Django 2.1.5 on 2020-03-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200309_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='6e07c346-87a2-4f90-80dd-98cc1ad1aa44', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_login',
            field=models.DateField(auto_now=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='http:127.0.0.1:8000/accounts/author/profile/6e07c346-87a2-4f90-80dd-98cc1ad1aa44/', max_length=100),
        ),
    ]
