# Generated by Django 2.1.5 on 2020-03-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200311_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='a89339ec-89c4-45aa-8805-b267e3ad6790', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='http:127.0.0.1:8000/accounts/author/profile/a89339ec-89c4-45aa-8805-b267e3ad6790/', max_length=100),
        ),
    ]
