# Generated by Django 2.1.5 on 2020-03-07 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default='False')),
                ('author_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_from', to=settings.AUTH_USER_MODEL)),
                ('author_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_a', to=settings.AUTH_USER_MODEL)),
                ('author_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
