# Generated by Django 2.1.5 on 2020-03-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend_displayName',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend_host',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend_id',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend_url',
        ),
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
