# Generated by Django 2.2.2 on 2020-04-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_auto_20200327_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='displayName',
            field=models.CharField(max_length=30),
        ),
    ]
