# Generated by Django 2.1.5 on 2020-03-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_friendrequest_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_approved',
        ),
    ]
