# Generated by Django 2.1.5 on 2020-03-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('image/jpeg;base64', 'Image/jpeg'), ('text/markdown', 'Markdown'), ('image/png;base64', 'Image/png'), ('text/plain', 'Plain text'), ('application/base64', 'Application')], default='text/plain', max_length=20),
        ),
    ]
