# Generated by Django 2.1.5 on 2020-03-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('md', 'text/markdown'), ('text', 'text/plain')], default='text', max_length=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text', 'text/plain'), ('md', 'text/markdown'), ('app', 'application/base64'), ('png', 'image/png;base64'), ('jpeg', 'image/jpeg;base64')], default='text', max_length=4),
        ),
    ]
