# Generated by Django 2.1.5 on 2020-02-19 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be_followed_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='AID2', to=settings.AUTH_USER_MODEL)),
                ('follower_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='AID1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBL', 'Public'), ('PRTS', 'Prviate to self'), ('PRTF', 'Private to friends'), ('PTFF', 'Private to friends of friends'), ('PTFL', 'Private to local friends')], default='PUBL', max_length=4),
        ),
    ]
