# Generated by Django 2.2.2 on 2020-04-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20200327_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('application/base64', 'Application'), ('image/jpeg;base64', 'Image/jpeg'), ('text/plain', 'Plain text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'Image/png')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(choices=[(False, 'Listed'), (True, 'Unlisted')], default=False),
        ),
    ]
