# Generated by Django 2.1.5 on 2020-02-19 00:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20200219_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
