# Generated by Django 2.2.2 on 2020-03-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20200324_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibleTo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('application/base64', 'Application'), ('text/plain', 'Plain text'), ('text/markdown', 'Markdown'), ('image/jpeg;base64', 'Image/jpeg'), ('image/png;base64', 'Image/png')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=False),
        ),
    ]
