# Generated by Django 2.2.2 on 2020-04-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20200401_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain Text')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Markdown'), ('image/png;base64', 'Image/png'), ('text/plain', 'Plain text'), ('image/jpeg;base64', 'Image/jpeg'), ('application/base64', 'Application')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=False),
        ),
    ]
