# Generated by Django 2.2.2 on 2020-03-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20200324_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('application/base64', 'Application'), ('text/plain', 'Plain text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'Image/png'), ('image/jpeg;base64', 'Image/jpeg')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
