# Generated by Django 2.2.2 on 2020-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20200324_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('image/jpeg;base64', 'Image/jpeg'), ('text/plain', 'Plain text'), ('application/base64', 'Application'), ('text/markdown', 'Markdown'), ('image/png;base64', 'Image/png')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(blank=True, default='https://peaceful-savannah-82754.herokuapp.com/posts/<django.db.models.fields.UUIDField>/', max_length=200),
        ),
    ]
