# Generated by Django 2.2.2 on 2020-03-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20200326_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain text'), ('image/jpeg;base64', 'Image/jpeg'), ('image/png;base64', 'Image/png'), ('application/base64', 'Application'), ('text/markdown', 'Markdown')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(default='https://peaceful-savannah-82754.herokuapp.com/posts/<django.db.models.fields.UUIDField>/', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=False),
        ),
    ]
