# Generated by Django 2.1.5 on 2020-03-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20200303_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('md', 'text/markdown'), ('text', 'text/plain')], default='text', max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='DEFAULT TITLE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Prviate to self'), ('FRIENDS', 'Private to friends'), ('FOAF', 'Private to friends of friends'), ('SERVERONLY', 'Private to local friends')], default='PUBL', max_length=10),
        ),
    ]
