# Generated by Django 2.2.2 on 2020-03-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20200326_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain Text')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('image/jpeg;base64', 'Image/jpeg'), ('text/markdown', 'Markdown'), ('image/png;base64', 'Image/png'), ('text/plain', 'Plain text'), ('application/base64', 'Application')], default='text/plain', max_length=20),
        ),
    ]
