# Generated by Django 2.1.5 on 2020-04-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20200401_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Markdown'), ('image/jpeg;base64', 'Image/jpeg'), ('application/base64', 'Application'), ('text/plain', 'Plain text'), ('image/png;base64', 'Image/png')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.TextField(blank=True),
        ),
    ]
