# Generated by Django 2.2.2 on 2020-04-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20200402_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Markdown'), ('image/jpeg;base64', 'Image/jpeg'), ('image/png;base64', 'Image/png'), ('text/plain', 'Plain text'), ('application/base64', 'Application')], default='text/plain', max_length=20),
        ),
    ]
