# Generated by Django 2.2.2 on 2020-03-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20200326_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('application/base64', 'Application'), ('text/plain', 'Plain text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'Image/png'), ('image/jpeg;base64', 'Image/jpeg')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='<function uuid4 at 0x1062feef0>', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(default='https://peaceful-savannah-82754.herokuapp.com/posts/<django.db.models.fields.CharField>/', editable=False, max_length=200),
        ),
    ]
