# Generated by Django 2.2.2 on 2020-03-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_auto_20200326_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain Text')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('image/png;base64', 'Image/png'), ('text/plain', 'Plain text'), ('application/base64', 'Application'), ('image/jpeg;base64', 'Image/jpeg'), ('text/markdown', 'Markdown')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='41fee15f-0791-4b05-8e78-0fae8851b726', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False),
        ),
    ]
