# Generated by Django 2.2.2 on 2020-04-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0009_auto_20200403_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain Text')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('image/png;base64', 'Image/png'), ('application/base64', 'Application'), ('image/jpeg;base64', 'Image/jpeg'), ('text/plain', 'Plain text'), ('text/markdown', 'Markdown')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=False),
        ),
    ]
