# Generated by Django 2.2.2 on 2020-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0010_auto_20200403_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('image/jpeg;base64', 'Image/jpeg'), ('text/plain', 'Plain text'), ('text/markdown', 'Markdown'), ('application/base64', 'Application'), ('image/png;base64', 'Image/png')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False),
        ),
    ]
