# Generated by Django 2.2.2 on 2020-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0014_auto_20200403_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('image/png;base64', 'Image/png'), ('text/markdown', 'Markdown'), ('text/plain', 'Plain text'), ('application/base64', 'Application'), ('image/jpeg;base64', 'Image/jpeg')], default='text/plain', max_length=20),
        ),
    ]
