# Generated by Django 2.1.5 on 2020-03-04 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0015_auto_20200304_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='author',
        ),
    ]
