# Generated by Django 2.1.5 on 2020-03-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0016_auto_20200304_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='be_followed_id',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower_id',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
