# Generated by Django 2.1.5 on 2020-03-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0023_auto_20200307_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(choices=[('TRUE', True), ('False', False)], default=False),
        ),
    ]
