# Generated by Django 2.1.5 on 2020-03-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0031_auto_20200309_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_type',
        ),
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text', 'text/plain'), ('md', 'text/markdown')], default='text', max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text', 'text/plain'), ('md', 'text/markdown')], default='text', max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
