# Generated by Django 2.1.5 on 2020-03-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0032_auto_20200311_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=False),
        ),
    ]
